name: Build and Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Cambiar para que coincida con go.mod

      - name: Install Dependencies (if any)
        run: |
          # Instala dependencias si tu proyecto las tiene
          # Ejemplo: apt-get update && apt-get install -y ...

      - name: Build Executables
        run: |
          chmod +x app-bluengo-worker/build.sh  # Dar permisos de ejecución al script
          ./app-bluengo-worker/build.sh  # Ejecutar el script

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bluengo-worker-executables
          path: app-bluengo-worker/dist  # Directorio donde se guardaron los ejecutables